### ISSUE TITLE
Map does not load

### ISSUE THREAD

**Issue by minakshibh** [Esri/arcgis-runtime-samples-ios#1007]
https://github.com/Esri/arcgis-runtime-samples-ios/blob/master/arcgis-ios-sdk-samples/Edit%20data/Edit%20and%20sync%20features/EditAndSyncFeaturesViewController.swift

EditAndSyncFeaturesViewController does not load the map and if I try to make the selection the app gets crashed.

**Comment by yo1995** [comment]
Hi, could you provide more information? Thanks.

**Platform Information**

* Version of SDK: 
* Version of iOS:
* Is it from the AppStore version or your own build: 
* Device:

**Steps to Reproduce**

**Comment by minakshibh** [comment]
Version of SDK: 100.9
Version of iOS: 14.2
Is it from the AppStore version or your own build; which branch you are using: I am using this sample only.
Device: iPhone XS, iPhone X, Simulator.

This is my layer url: https://services.arcgis.com/455ANVnHBozNhUJX/arcgis/rest/services/FACILITIES/FeatureServer/0

**Comment by yo1995** [comment]
Thanks for the details. I tried with the feature service [URL](https://services.arcgis.com/455ANVnHBozNhUJX/arcgis/rest/services/FACILITIES/FeatureServer/0) you provided above, and it seems not to support geodatabase sync operation. See the `Supported Operations` section in the bottom of the page. Could you verify that?

In terms of the map's crashing issue: this sample loads the basemap from a local tile package `SanFrancisco.tpk` [here](https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Shared%20resources/Tile%20packages). Are you including this tile package in your project?
You could also create and load your own tile package as the basemap, or use one of the Esri basemaps for testing purposes. (e.g. `let map = AGSMap(basemap: .streets())`).

Let me know if this is your case, and if not we can try to figure out other problems. 🙂

**Comment by yo1995** [comment]
Close due to inactivity.
