### ISSUE TITLE
iOS WebMap

### ISSUE THREAD

**Issue by aliawais** [Esri/arcgis-runtime-samples-ios#1012]
Hi,

It is more of a question rather than an issue.

Is there still support for Webmap in iOS? If yes, if there is sample please provide.

I was looking at https://developers.arcgis.com/ios/10-2/swift/guide/viewing-web-map.htm it refers to using **AGSWebMap** which I cant find.

It redirects for sample on http://www.arcgis.com/home/item.html?id=d76ed99f71e24116b324ff624a194ef9 and the URL for the repo is following but it give 404. 

https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/WebmapSample

**Reason**
Current implementation is done using _AGSMapView_ and layer URLs are in config file and layers can be shown/hidden using. Now we need to support multiple clients and each client can have their own maps and layers, client will be determined after login. So we were thinking to load client's map using their MapId.

**Comment by yo1995** [comment]
Hi @aliawais , I'm not quite sure about your problem. Can you try to load a webmap with its portal item ID? e.g.

```swift
let portal = AGSPortal.arcGISOnline(withLoginRequired: false)
let portalItem = AGSPortalItem(portal: portal, itemID: yourPortalItemID)
let map = AGSMap(item: portalItem)
mapView.map = map
```

**Comment by aliawais** [comment]
Is portalItemId different from MapId?

Is there a complete sample using this approach and also showing/hiding available layers?

**Comment by yo1995** [comment]
> Is portalItemId different from MapId?

I think they are the same thing.

> Is there a complete sample using this approach and also showing/hiding available layers?

You may take a look at 

- [Feature collection layer (portal item)](https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Features/Feature%20collection%20layer%20(portal%20item))
- [Change sublayer visibility](https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Layers/Change%20sublayer%20visibility)
- [Manage operational layers](https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Maps/Manage%20operational%20layers)

for some inspirations. 

AFAIK there isn't a sample that demonstrates the workflow to load multiple layers from ArcGIS Online and control their visibility. I also asked our team to see if they have suggestions.

**Comment by aliawais** [comment]
@yo1995 thank you.

I tried using the mapId with login and without login it did not work.

I will look into the samples and hope to find something we need.

**Comment by yo1995** [comment]
> @yo1995 thank you.
> 
> I tried using the mapId with login and without login it did not work.
> 
> I will look into the samples and hope to find something we need.

Sure. Please feel free to reopen this issue if you've more questions, and I'll get you posted when I receive feedback regarding the `AGSWebMap` class.

**Comment by nixta** [comment]
@aliawais You could take a look at this sample: https://developers.arcgis.com/ios/latest/swift/sample-code/open-map-url/

That takes the URL to the item page for a web map in ArcGIS and opens it. Does that help?

**Comment by yo1995** [comment]
As Nick indicated - In addition, consider taking a look at these 2 samples:

- [Open map (URL)](https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Maps/Open%20map%20(URL))
    This sample opens 3 maps from ArcGIS Online.
- [Token authentication](https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Cloud%20and%20portal/Token%20authentication)
    This sample opens a [portal item that requires authentication](https://www.arcgis.com/home/item.html?id=e5039444ef3c48b8a8fdc9227f9be7c1). When a resource requires login, it will prompt an alert to let you provide credentials.

Hope it helps.

**Comment by aliawais** [comment]
Thanks @nixta  and @yo1995  will definitely have a look into these.

**Comment by aliawais** [comment]
Thanks guys it worked: I used 
let portal = AGSPortal.arcGISOnline(withLoginRequired: true)
        let portalItem = AGSPortalItem(portal: portal, itemID: _mapId_)
        let map = AGSMap(item: portalItem)

If i have the authentication token how can I avoid the popup?

**Comment by aliawais** [comment]
@nixta  @yo1995 
Hi guys,

I am loading the map using follwing:
```
let portal = AGSPortal(url: portalURL, loginRequired: true)
        portal.credential = agsCredential
        let portalItem = AGSPortalItem(portal: portal, itemID: mapId)
        let map = AGSMap(item: portalItem)
        esriMapView.map = map
```
where agsCredential are created using a token from API and referer that the app sends in request. The login popup still shows up for "You need to sign in to access www.arcgis.com"

If add another port as follows before the above code it works to load layers and map.
```
let arcGISPortal = AGSPortal.arcGISOnline(withLoginRequired: true)
            arcGISPortal.credential = agsCredential
            arcGISPortal.load { (error) in
                if let _ = error {
                    print("Failed loading/signing to acrGISOnline")
                }
            }

```

But when I try to fetch basemaps using code below it shows login popup again but to sign in to portal.
```
        portal.load { (error) in
            if error == nil {
                portal.fetchBasemaps { (basemaps, err) in
                
            }
        }
```

**Comment by nixta** [comment]
> @nixta @yo1995
> Hi guys,
> 
> I am loading the map using follwing:
> 
> ```
> let portal = AGSPortal(url: portalURL, loginRequired: true)
>         portal.credential = agsCredential
>         let portalItem = AGSPortalItem(portal: portal, itemID: mapId)
>         let map = AGSMap(item: portalItem)
>         esriMapView.map = map
> ```

What is the portalURL? And please provide details on how you’re getting the token. 

Building a credential using the token is a less common approach (and you should use the AGSAuthenticationManager challengeHandler pattern if you’re doing that, for seamless token refreshes).

It sounds to me like you might be getting a token from one portal and using it on another.

**Comment by aliawais** [comment]
Hi @nixta @yo1995 

Before loading a map, the app makes calls one of our APIs and we pass a 'referer' in header. The API uses ESRI/ArcGIS service to obtain a token for the provided referer. Then API returns us a mapId, portalURL, token, tokenExpiry. The same API is used by our front-end (web).

JSON format of response:
{
  "gisBaseUrl": "portalURL",
  "token": {
    "token": "",
    "expires": 1606815960364,
    "ssl": true
  },
  "authRequiredPaths": [
    "/portal",
    "/server/rest/services"
  ],
  "gisPortalPath": "/portal",
  "defaultWebMapId": "mapId"
}

One suggestion from we developer was that they also sign in to authRequiredPaths as it might be casing issue, **how to do that?**

The portalURLs (gisBaseURL) could be one of the following format:
- https://atlas.{client Name}.com
- https://{client Name}.maps.arcgis.com

Then use the portal URL and 

```
agsCredential = AGSCredential(token: portalToken, referer: referer)
let portal = AGSPortal(url: portalURL, loginRequired: true)
        portal.credential = agsCredential
        let portalItem = AGSPortalItem(portal: portal, itemID: mapId)
        let map = AGSMap(item: portalItem)
        esriMapView.map = map
        map.load { (error) in 
              // handle error or handle successfully loaded map
              // load base maps
}
```

I tried one thing with **AGSAuthenticationManager**, after getting token from our API, set **AGSAuthenticationManager.shared().delegate** to self and then in one of the delegates did following:
    ```func authenticationManager(_ authenticationManager: AGSAuthenticationManager, didReceive challenge: AGSAuthenticationChallenge) {
        agsCredential?.token = esriAuthViewModel.portalToken()
        challenge.continue(with: agsCredential)
    }
```
The strange thing I noticed was that `agsCredential` is class level variable, and its token was getting null.

So I need to use the token from our API and dont want to show the authentication challenge popup, if there any implementation suggestion please provide, can you also please refer to a proper implementation of using AGSAuthenticationManager.

**Comment by nixta** [comment]
There is a lot going on here, and it's not really relevant to this repo. Might be worth picking the conversation up over at the [iOS Runtime forum](https://community.esri.com/t5/arcgis-runtime-sdk-for-ios/bd-p/arcgis-runtime-sdk-for-ios-questions). But…

Firstly, a token obtained for `https://atlas.{client Name}.com` (which, by the looks of things, is an on-premise ArcGIS Enterprise instance) will not work at `https://{client Name}.maps.arcgis.com`.

`agsCredential` must be something in your codebase. Not sure what that is or how it's created. You can look at the [`proposedCredential`](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_credential.html#aec8bf10af5dc8fb5a8302ec0520ad897) that is passed to the challengeHandler. Set the token on that. However, you still want to make sure that the token was generated for the right service/portal.

You might find some useful info [here](https://gist.github.com/nixta/33afa1a17d7a9ea85f0d2d601e55a79f) too.

You appear to be using challengeHandler correctly, btw. Just not sure if passing back `agsCredential` is a good thing since we don't know what it is or where it comes from in your codebase.

**Comment by nixta** [comment]
What is the URL that is being used to generate the token?

**Comment by nixta** [comment]
It could also be that the token is expired. If you use the username and password, Runtime will automatically get a new token if the old one expires.

**Comment by aliawais** [comment]
@nixta 

Token is generated for each portal when it changes. The URL for one of them is 
https://atlas.{clientName}.com/portal/sharing/rest/generateToken

The token is generated at time app make the call to our API, and its has an expiry of 24hours.

**Comment by nixta** [comment]
> @nixta
> 
> Token is generated for each portal when it changes. The URL for one of them is
> [https://atlas.{clientName}.com/portal/sharing/rest/generateToken](https://atlas.%7BclientName%7D.com/portal/sharing/rest/generateToken)
> 
> The token is generated at time app make the call to our API, and its has an expiry of 24hours.

Then in the code above:

```
let portal = AGSPortal(url: portalURL, loginRequired: true)
        portal.credential = agsCredential
        let portalItem = AGSPortalItem(portal: portal, itemID: mapId)
        let map = AGSMap(item: portalItem)
        esriMapView.map = map
```

what is the `portalURL`? If it's not `atlas.{clientName}.com` or if the token was not obtained using credentials that authorize access to the `mapId` web map, then the credential will not work and you will be prompted.

**Comment by aliawais** [comment]
The token is generated for that portalURL which we get in the response and the mapId is associated with that token and portal.

The thing is when create agsCredetails using user name and password it works fine. Can you please link me to the sample using the Authentication manager.

**Comment by nixta** [comment]
Unfortunately we don't have an AuthenticationManager sample that covers using credentials with token.

One thought. You said this:

> I am loading the map using follwing:
> ```
> let portal = AGSPortal(url: portalURL, loginRequired: true)
>         portal.credential = agsCredential
>         let portalItem = AGSPortalItem(portal: portal, itemID: mapId)
>         let map = AGSMap(item: portalItem)
>         esriMapView.map = map
> ```
> where agsCredential are created using a token from API and referer that the app sends in request. The login popup still shows up for "You need to sign in to access www.arcgis.com"
> 
> If I add another portal (not used afterwards) as follows before the above code it works to load layers and map.
> ```
> let arcGISPortal = AGSPortal.arcGISOnline(withLoginRequired: true)
>             arcGISPortal.credential = agsCredential
>             arcGISPortal.load { (error) in
>                 if let _ = error {
>                     print("Failed loading/signing to acrGISOnline")
>                 }
>             }
> 
> ```

Is `agsCredential` the same when applied to both portals?

**Comment by aliawais** [comment]
I used that approach for portal https://{client Name}.maps.arcgis.com, and the agsCredential was same for arcGISOnline(withLoginRequired: true)


For portal https://atlas.{client Name}.com it works without the extra AGSPortal.arcGISOnline(withLoginRequired: true). And both the portal (https://atlas.{client Name}.com and https://{client Name}.maps.arcgis.com) have different token generated fro our API.

At one time I using one portalURL and one mapId, for simplicity if UserA logs in to the app we use https://atlas.{client Name}.com and if UserB logs in we use  https://atlas.{client Name}.com

**Comment by nixta** [comment]
To confirm:

This does NOT work:

Display a map from https://{client Name}.maps.arcgis.com.
```
// portalURL = https://{client Name}.maps.arcgis.com
// agsCredential is a token obtained from www.arcgis.com
let portal = AGSPortal(url: portalURL, loginRequired: true)
        portal.credential = agsCredential
        let portalItem = AGSPortalItem(portal: portal, itemID: mapId)
        let map = AGSMap(item: portalItem)
        esriMapView.map = map
```

This DOES work:

Display a map after loading the www.arcgis.com portal with a separate credential first:
```
// agsCredential is obtained from www.arcgis.com
let arcGISPortal = AGSPortal.arcGISOnline(withLoginRequired: true)
            arcGISPortal.credential = agsCredential
            arcGISPortal.load { (error) in
                if let _ = error {
                    print("Failed loading/signing to acrGISOnline")
                }
            }
// portalURL = https://{client Name}.maps.arcgis.com
// agsCredential is the same as above
let portal = AGSPortal(url: portalURL, loginRequired: true)
        portal.credential = agsCredential
        let portalItem = AGSPortalItem(portal: portal, itemID: mapId)
        let map = AGSMap(item: portalItem)
        esriMapView.map = map
```

**Comment by aliawais** [comment]
yes

**Comment by aliawais** [comment]
Posting my solution here, may its helpful for others.

Once our API returns the token it generated from ARCGisPortal, the controller sets its self as delegate to following `AGSAuthenticationManager.shared().delegate = self`

`AGSPortal` is created without setting its `AGSCredential` property and I do following:

```
let portal = AGSPortal(url: portalURL, loginRequired: true)
        portal.load { (error) in
            if let _ = error {
                self.delegate?.mapLoadingFailed()
            } else {
                let portalItem = AGSPortalItem(portal: portal, itemID: mapId)
                self.loadWebMap(portalItem: portalItem)
                self.loadBaseMaps(portal: portal)
            }
        }
```

Following is how I have handled one of the delegate methods

```
func authenticationManager(_ authenticationManager: AGSAuthenticationManager, didReceive challenge: AGSAuthenticationChallenge) {
            // creating credentials from token returned from our API
            let agsCredentials = AGSCredential(token: credentialToken, referer: referer)
            challenge.continue(with: agsCredentials)
        }
    }
```

So now whenever the credentials challenge is received, the method continue with the AGSCredentials.
