### ISSUE TITLE
Online Feature Layer Editing sample not reading Status field domain

### ISSUE THREAD

**Issue by nixta** [Esri/arcgis-runtime-samples-ios#104]
In the [Feature Layer Editing Sample](https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/FeatureLayerEditingSample) (swift and objective-c) the editor is not reading the `Status` field's domain.

I see that the field is set to `New` for example…

![2015-01-26_20-02-12](https://cloud.githubusercontent.com/assets/25374/5911667/b75554b8-a596-11e4-8656-6973e88314dc.png)

…but when I tap it to edit it, I am presented with a text field with the digit `1` in it:

![2015-01-26_20-02-22](https://cloud.githubusercontent.com/assets/25374/5911673/c05e2ec2-a596-11e4-9fe6-53e831218a0a.png)

Surely I should get to choose from `New`, `Open`, and `Closed` as in the [Web Viewer](http://www.arcgis.com/home/webmap/viewer.html?webmap=b31153c71c6c429a8b24c1751a50d3ad)?

**Comment by dg0yal** [comment]
Thanks for reporting. This appears to be a bug in the popup. We'll look into it

**Comment by dg0yal** [comment]
This is fixed in 100.x
