### ISSUE TITLE
iOS 8 - Add permission to post local notification

### ISSUE THREAD

**Issue by dg0yal** [Esri/arcgis-runtime-samples-ios#105]
iOS 8 requires developers to use this - https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/#//apple_ref/occ/instm/UIApplication/registerUserNotificationSettings:

We need to update the samples that post local notifications
- DownloadTileCache
- OfflineFeatureEditing

**Comment by singhgag** [comment]
Done.

@dg0yal please verify. 

Pull request: https://github.com/Esri/arcgis-runtime-samples-ios/pull/107

**Comment by singhgag** [comment]
@dg0yal can we close this?

**Comment by dg0yal** [comment]
Yes. Closed.
