### ISSUE TITLE
This copy of libswiftCore.dylib requires an OS version prior to 10.14.4.

### ISSUE THREAD

**Issue by kgb16** [Esri/arcgis-runtime-samples-ios#1071]
When i compile this example project on XCode, this error found:"This copy of libswiftCore.dylib requires an OS version prior to 10.14.4.". My Mac OS version is 10.15.7. So, any suggest?

**Comment by yo1995** [comment]
Hi, can you please share which Xcode version are you using? i.e. Xcode version, CLI version, `xcode-select -p` output, etc.

**Comment by kgb16** [comment]
Xcode 12.4
Build version 12D4e
/Applications/Xcode.app/Contents/Developer

**Comment by yo1995** [comment]
Can you give this test app a try to see if it builds, and shows a topo map? Thanks.

[Test App.zip](https://github.com/Esri/arcgis-runtime-samples-ios/files/6497924/Test.App.zip)

**Comment by kgb16** [comment]
使用您发的Test包可以正常编译运行。我发现两个包不一样的地方在于我这里跑example是按照：“Building Samples Using CocoaPods”指引来配置依赖库的。你所发的包是另外一种配置："Building Samples Using Swift Package Manager"

**Comment by yo1995** [comment]
晚上我用自己电脑尝试了一下CocoaPods没遇到问题。明天我再新建一个项目，配置用pods安装SDK试试。请稍等

我的环境是

- OSX 15.7
- Xcode 12.4 (12D4e)
- CocoaPods 1.10.1 (`pod --version`)

**Comment by kgb16** [comment]
新建项目是可以正常运行的，只是运行arcgis-runtime-samples-ios这个工程会报错

**Comment by yo1995** [comment]
抱歉，还是没能复现。明天我再请同事帮忙试一试 😓 

可以看一下这个帖子里的讨论，看看是否本地存在多个版本的Swift compiler？https://forums.swift.org/t/error-running-sourcekit-lsp-in-macos/26181/7

**Comment by yo1995** [comment]
今天同事测试用pods编译成功。他的环境

- Big Sur
- Xcode 12.2
- iOS 14.2 iPad真机

他在更新pods时提示了

```txt
[!] CocoaPods could not find compatible versions for pod "ArcGIS-Runtime-Toolkit-iOS":
  In Podfile:
    ArcGIS-Runtime-Toolkit-iOS (~> 100.11)
None of your spec sources contain a spec satisfying the dependency: `ArcGIS-Runtime-Toolkit-iOS (~> 100.11)`.
You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```

按照提示升级repo后能够build成功。

您是否有别的电脑可以测试编译呢？谢谢

**Comment by yo1995** [comment]
你好，问题有没有解决或者进展？谢谢～

**Comment by yo1995** [comment]
Close due to inactivity. Feel free to reopen or create a new issue!
