### ISSUE TITLE
For the "Display Device Location with NMEA Data sources", Trimble R12 was not show in the list

### ISSUE THREAD

**Issue by yxliwhu** [Esri/arcgis-runtime-samples-ios#1078]

**Comment by yo1995** [comment]
Hi,

Currently this sample supports 3 external Bluetooth devices: SXBlue, EOS and BadElf only for demonstrating purposes.

If you want to try out the Trimble device, 

- either add the protocols to this section in `Info.plist`, i.e. `com.trimble.correction` and `com.trimble.command`

https://github.com/Esri/arcgis-runtime-samples-ios/blob/61c82de7f8d620cf7edb54e509f98c2f0606a713/arcgis-ios-sdk-samples/Info.plist#L118

- or use the [Esri Field Maps app](https://apps.apple.com/us/app/arcgis-field-maps/id1515671684)

**Comment by yxliwhu** [comment]
Thanks for the reply. Now the Trimble could connect to the iOS device. But I find the AGSNMEALocationDataSource seem to not update automatically. Anyone have test this new function in SDK 100.11?

**Comment by yo1995** [comment]
> I find the AGSNMEALocationDataSource seem to not update automatically

Can you explain a bit more here? What do you mean by *not update automatically*? Do you mean

- The location indicator (blue dot) is not showing up
- No updates are provided by the `locationDidChange` delegate method
- The device is not pushing data to the location data source, etc.

Thanks.

**Comment by yxliwhu** [comment]
@yo1995 Sorry for the misunderstanding. For my case, there are no updates are provided by the locationDidChange delegate method. I think this problem maybe caused by the second reason you mentioned. Thanks for your help, I look forward for your response tomorrow.

**Comment by yo1995** [comment]
While waiting for feedback, (having done some preliminary research) I found that Trimble R-series do work differently than the built-in support for EOS, SXBlue or BadElf (which only requires Bluetooth connection). It seems Trimble requires some config steps that possibly involve...

- Trimble Mobile Manager
- GNSS Configuration and some parameters
- Multiple bluetooth protocols included in `Info.plist`

Hope I'll be able to come up with a step by step instruction for setting up Trimble.

**Comment by yo1995** [comment]
@yxliwhu Just got feedback from Trimble folks. They explained that only Trimble R1 and R2 has partial NMEA output support in their firmware, but not the "non-GIS R-series receivers like the R10/12/12i". 😞  Therefore it seems it's currently not possible to use the Runtime NMEA APIs together with your Trimble R12.

Please let me know if you have further questions!

**Comment by yo1995** [comment]
Close due to inactivity. Feel free to reopen or create a new issue!
