### ISSUE TITLE
[Feature] How can I create a heatmap ?

### ISSUE THREAD

**Issue by rameezhandel** [Esri/arcgis-runtime-samples-ios#1144]
**No documentation for creating heatmap.**

**Step by step documentation for creating heatmap**

**Still not found a solution**

**Comment by yo1995** [comment]
Hi Rameez,

Runtime doesn't support creating a heatmap yet. You'll need to create the heatmap in ArcGIS Pro or ArcGIS Online, save it as a webmap or a feature layer, then display in Runtime.

For instance, if you want to display this public [Manhattan Coffee Heatmap](https://www.arcgis.com/home/item.html?id=67c10b4b5d3d4eab86b6aaf41d9dcba6)

```swift
import UIKit
import ArcGIS

class ViewController: UIViewController {
    @IBOutlet var mapView: AGSMapView! {
        didSet {
            mapView.map = AGSMap(url: URL(string: "https://www.arcgis.com/home/item.html?id=67c10b4b5d3d4eab86b6aaf41d9dcba6")!)
        }
    }
}
```

**Comment by rameezhandel** [comment]
Thank you.
