### ISSUE TITLE
Issue in accessing rest API

### ISSUE THREAD

**Issue by sabby3861** [Esri/arcgis-runtime-samples-ios#115]
I am trying to use the rest API for arcgis. This api is in already developed project. The time I am consuming it is showing NSURLErrorDomain -1005.
I think this api is deployed in rest server. Can you please help me in resolving this issue.
Below is the one of the API used in the project and I don't have any access to the developer who has already used this API.
http://services1.arcgis.com/ImVsa1aCTpFAYBU0/arcgis/rest/services/Span/FeatureServer/0

**Comment by nixta** [comment]
Can you be more specific about how this relates to this repo?

If it's not, you should ask the question over on [GeoNet's iOS SDK Forum](https://geonet.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-ios/content).

If you do that, please provide more info though. For example: Does the other project still work? What are you trying to do with the service?
