### ISSUE TITLE
Load ArcGIS shapefiles (.shp) as layers

### ISSUE THREAD

**Issue by chriscamed** [Esri/arcgis-runtime-samples-ios#128]
It would be great to include the feature of loading shapefiles as layers. ArcGIS SDK for Android has this functionality with this method: public ShapefileFeatureTable(@NotNull String pathToShapeFile)

**Comment by dg0yal** [comment]
Shapefiles are supported as of 100.2 version.
Check out the sample - https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Features/Feature%20layer%20(shapefile)
