### ISSUE TITLE
Swift Samples do not run in Xcode 7.2.1, Swift 2.1.1

### ISSUE THREAD

**Issue by dirtsniffer** [Esri/arcgis-runtime-samples-ios#139]
None of the Swift Samples run in Xcode 7.2.1, Swift 2.1.1.
Some but not all of the issues

- Bitcode needs to be set to "NO"
- something with "as" and Set
- println needs to be "print"

**Comment by singhgag** [comment]
https://github.com/Esri/arcgis-runtime-samples-ios/pull/141

**Comment by singhgag** [comment]
@dirtsniffer Can you close the issue if everything is working for you now?
