### ISSUE TITLE
Sample showing how to implement a custom datasource for map's location display

### ISSUE THREAD

**Issue by dg0yal** [Esri/arcgis-runtime-samples-ios#19]
For example, a datasource that pulls data from mapmyrun and navigate along your recent runs.

**Comment by yo1995** [comment]
With the latest update in U9, the `Show location history` sample uses a custom mock location datasource. https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Maps/Show%20location%20history
