### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by ozcan-durak** [Esri/arcgis-runtime-samples-ios#217]
When will you release swift 3.0 samples. and SDK to work with Swift 3.0

Regards

**Comment by stonetip** [comment]
This is really important. Please make it a priority.

**Comment by dg0yal** [comment]
Yes, we are working on new samples for the upcoming release, they will initially be in Swift 2.3, but in a short time after that we will upgrade the new samples to Swift 3.0

**Comment by stonetip** [comment]
FWIW, I've found most samples have worked okay, especially when the code is run through Xcode 8.1's conversion to 3.0 syntax. Still, it will be useful to have more samples and to have them in 3.0 syntax. It's helpful in being able to quickly experiment with and understand the utility of various Runtime features.

Thanks!

**Comment by dg0yal** [comment]
Samples have been updated to swift 3
