### ISSUE TITLE
Map issue delegate method not called in Swift 3.0 , iOS 10

### ISSUE THREAD

**Issue by JayMehta711** [Esri/arcgis-runtime-samples-ios#220]
- callout(callout: AGSCallout!, willShowForFeature feature: AGSFeature!, layer: AGSLayer!, mapPoint: AGSPoint!)
- This delegate method not called when tap on Marker. 
- In this case i am not getting this details.
  let graphic = feature as! AGSGraphic

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
-  AGSCalloutDelegate,AGSLocatorDelegate,AGSMapViewLayerDelegate,AGSLayerDelegate
  self.mapView.callout.delegate = self;
  self.mapView.layerDelegate = self;
  -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Any one know Why delegate method not called!!!

**Comment by yo1995** [comment]
Close due to inactivity. Please reopen if needed.
