### ISSUE TITLE
OfflineRoutingSample crash on physical devices running IOS 10.0.2 , 9.3.2 .

### ISSUE THREAD

**Issue by abdelrahman-badary** [Esri/arcgis-runtime-samples-ios#226]
I can't run the OfflineRoutingSample (objective-c) on physical devices running IOS 10.0.2 , 9.3.2 , when i add another point to create a route an EXC_BAD_ACCESS is thrown from "Esri_runtimecore::Network_analyst::Traversal_result::get_partial_edge_geometry_" , however it is working fine on the 10.0 simulator , and on a physical device running 9.3.4 , anyone facing the same issue ?

Note: i am running the 10.2.5 IOS SDK , and Xcode 8 . 

<img width="1279" alt="screen shot 2016-10-23 at 4 48 46 pm" src="https://cloud.githubusercontent.com/assets/8076566/19627147/a95c63de-9940-11e6-8ccb-068f6e3e2f36.png">

**Comment by goldenlimit** [comment]
Based on this geonet thread:https://geonet.esri.com/thread/175740#comment-602963
This is a known issue with 64 bit devices 
 
Can you try this workaround? Build the project with only 32 architectures. You can then run the app on all devices without a crash - the trade off being you would be unable to benefit from 64-bit computing.

**Comment by abdelrahman-badary** [comment]
It will work fine on 32 bit architectures but i wouldn't call this a workaround because the Appstore will not accept applications that supports 32 bit applications only , in other words 64 bit architectures must be supported in order to distribute on the Appstore .

**Comment by EddyLiu1001** [comment]
Hi abdeIrahman, I have met the same problem, have you find way to resolve this problem yet?

**Comment by abdelrahman-badary** [comment]
@EddyLiu1001 Hello mate, no i haven't found any useful solution to that problem other than the one suggested above, they released a new version of the SDK but i haven't tried it yet .

**Comment by EddyLiu1001** [comment]
@abdeIrahman,I also notice they have released a new version 100.0.0.But in their release note,they haven't mention this issue.I have downloaded the new version, but I don't know after I install the new version sdk,whether I can turn back to version 10.2.5 if I encounter some new problems.

**Comment by EddyLiu1001** [comment]
@goldenlimit  change structure to 32-bit can avoid this problem, but in that way,App will not be able to be put on APP Store.Any other suggestion?

**Comment by xianning** [comment]
@goldenlimit I find that  that the SDK supports 32 bit applications only , in other words 64 bit architectures must be supported in order to distribute on the Appstore .Could you give me some advice?

**Comment by goldenlimit** [comment]
@EddyLiu1001 @xianning We just released the new version of SDK 100.0, What about try with the new version of SDK? https://developers.arcgis.com/ios/
AGSRoute: https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_route.html

**Comment by goldenlimit** [comment]
Hi @EddyLiu1001 You can always retrieve back to the 10.2.5, as long as you just reinstall the 10.2.5 pkg file again on your mac and it will overwrite your current version of SDK in your mac.

**Comment by EddyLiu1001** [comment]
@goldenlimit  many thanks,I will try this issue in version 100.0.0

**Comment by abdelrahman-badary** [comment]
This issue is resolved in version 100.0
