### ISSUE TITLE
Property 'map' not found

### ISSUE THREAD

**Issue by mrimadali** [Esri/arcgis-runtime-samples-ios#236]
Hi 

After integrating the maps using cocoa pods, I have imported the following:
`#import <ArcGIS/ArcGIS.h>`
In storyboard file, I've added a UIView element into view controller, changed the class name as AGSMapView & created an outlet.

When I try to use the "**self.mapView.map**", it throws an error saying the **_property map not found on object of type AGSMapView_**. Please clarify. 

I was referring to the _https://developers.arcgis.com/ios/latest/swift/guide/develop-your-first-map-app.htm_

Attached is the screen shot for reference.
<img width="883" alt="screen shot 2016-12-12 at 1 42 51 pm" src="https://cloud.githubusercontent.com/assets/7879031/21094742/c1eb8e40-c071-11e6-86b4-593059f09979.png">

**Comment by singhgag** [comment]
@mrimadali What version of the SDK are you using?

**Comment by mrimadali** [comment]
Latest one, as I was using cocoapods to download the SDK.

**Comment by singhgag** [comment]
You mean 100.0.0? I asking because we didn't have the concept of `AGSMap` as a separate object in version 10.2.x.

**Comment by mrimadali** [comment]
Not sure, where to check the version.
I have downloaded the latest one using:
pod 'ArcGIS-Runtime-SDK-iOS'
Pls advice.

**Comment by singhgag** [comment]
One way to check would be to see if you have `AGSMap.h` file in the `Headers` folder. Location to the `Headers` folder: `$HOME/Library/SDKs/ArcGIS/iOS/Frameworks/Static/ArcGIS.framework/Headers`

**Comment by singhgag** [comment]
You can get the version number from the `version.txt` file located at `$HOME/Library/Application Support/AGSiOSRuntimeSDK/`

**Comment by mrimadali** [comment]
FYI, I don't have a file AGSMap.h.

**Comment by singhgag** [comment]
Can you share your podfile?

**Comment by mrimadali** [comment]
Here you go:

> platform :ios, '9.0'
> target 'AlexaTest' do
> pod 'ArcGIS-Runtime-SDK-iOS'
> end

**Comment by singhgag** [comment]
Try putting the version number along with the pod name. As below.
```
platform :ios, '9.0'
target 'AlexaTest' do
pod 'ArcGIS-Runtime-SDK-iOS', '~> 100.0'
end
```

**Comment by mrimadali** [comment]
It works, Thanks 👍
