### ISSUE TITLE
I have installed SDK, I have cloned the project from github still I'm getting error.

### ISSUE THREAD

**Issue by harshchitrla** [Esri/arcgis-runtime-samples-ios#237]
/Users/{Home}/Library/Developer/Xcode/DerivedData/arcgis-ios-sdk-samples-evftpkeyioizojaenycmfrtwgnln/Build/Products/Debug-iphonesimulator/arcgis-ios-sdk-samples.app/ArcGIS.bundle/Directions/NA Campus/pl.json: No such file or directory

**Comment by singhgag** [comment]
@harshchitrla What version of the SDK are you using?

**Comment by harshchitrla** [comment]
I'm using ArcGIS_Runtime_SDK_iOS_100_0_0 .

**Comment by singhgag** [comment]
Did you try clearing your derived data folder? If not follow the instructions on this [post](http://stackoverflow.com/a/40278559). Please close Xcode before deleting the folders inside derived data folder.

**Comment by philium** [comment]
Closing. If this is still a problem, please open a new issue.
