### ISSUE TITLE
Credential method is missing iOS 100.0.0 SDK

### ISSUE THREAD

**Issue by ikbalyasarGis** [Esri/arcgis-runtime-samples-ios#239]
Hi,
In its previous version we using,
`" let tiledLayer = AGSTiledMapServiceLayer(url :  url, credential :  creed)!" `

But I could not use this feature in the new version (100.0.0)

How to use encrypted service this version (100.0.0)

**Comment by dlednik** [comment]
@ikbalyasarGis 

It has been replaced with `AGSArcGISTiledLayer`

```Swift
let layer = AGSArcGISTiledLayer(url: url)
layer.credential = credentials
```

**Comment by ikbalyasarGis** [comment]
Thanks for fast answer. But this information dont exist in documents.
"https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_arc_g_i_s_tiled_layer.html"

**Comment by dlednik** [comment]
@ikbalyasarGis what information are you referring to?
That it replaced `AGSTiledMapServiceLayer` layer?

**Comment by ikbalyasarGis** [comment]
I'm referring AGSArcGISTiledLayer doesnt have credential property at developer documents. I've mentioned link above.

**Comment by dlednik** [comment]
I see, good point. That is inherited from `AGSRemoteResource` class but is not exposed in the doc.

**Comment by dlednik** [comment]
I logged internal issue for this to be addressed. Thank you for the feedback 👍

**Comment by ikbalyasarGis** [comment]
Thanks dlednik
