### ISSUE TITLE
Make Raster Renderer samples more interactive

### ISSUE THREAD

**Issue by nixta** [Esri/arcgis-runtime-samples-ios#246]
Could we make the Renderer properties panels not mask out the underlying layer? That way when we move sliders around we can see the effect on the underlying layer.

Also, unless you know what you're doing, some of the demos that have manual inputs are very opaque. It's not clear what are suitable values for some of the numeric inputs. Could the panels suggest some values perhaps or have some presets?

**Comment by yo1995** [comment]
Close due to inactivity.
