### ISSUE TITLE
How to customize symbols?

### ISSUE THREAD

**Issue by DhbStudy** [Esri/arcgis-runtime-samples-ios#252]
Hello,
        I'd like to render the map elements more flexibly by using symbol. I find that the AGSTextSymbol has lots of properties, but for other symbols like AGSLineSymbol I don't find the way to realize complex display. In fact, I really want to know how to customize symbols.

**Comment by dg0yal** [comment]
A neat way to achieve complex affects is by using `AGSCompositeSymbol` to combine a number of point, line and polygon symbols.  https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_composite_symbol.html
