### ISSUE TITLE
No such module 'ArcGIS'

### ISSUE THREAD

**Issue by bibinjacobpulickal** [Esri/arcgis-runtime-samples-ios#290]
It is said that you just need to download the project and run it on xcode. But, the sample project doesn't run on Xcode 8.3.3. MacOS 10.12. Shows swift compiler error No such module 'ArcGIS'. Found that the ArcGIS.framework file that needs to be included along with the sample project is missing.

**Comment by rlaguilar** [comment]
Any update in this?

**Comment by singhgag** [comment]
@bibinjacobpulickal @rlaguilar 
As listed in the `Requirements` section of the [Readme](https://github.com/Esri/arcgis-runtime-samples-ios/blob/master/README.md#requirements), you need to download and install the Runtime SDK for iOS. You can find more details [here](https://developers.arcgis.com/ios/latest/swift/guide/install.htm)

**Comment by esreli** [comment]
@bibinjacobpulickal @rlaguilar as a follow up to @singhgag's note, there are two ways to install the ArcGIS Runtime SDK for iOS. **Please note**: the application is currently configured for a manual install. 

If you prefer to install using Cocoapods, you must follow these steps:

1. Delete `ArcGIS.framework` from the project (it should be red & is the last item in the `arcgis-ios-sdk-samples` group folder.
2. **Click**: [Your Target] -> Build Settings
3. **Under**: Search Paths -> Framework Search Paths, **delete** the second item `$(USER_LIBRARY_DIR)/SDKs/ArcGIS/iOS/Frameworks/Static`
4. Create a `Podfile` and to it add `pod 'ArcGIS-Runtime-SDK-iOS', '100.1.1'`
5. Run `$ pod install`

And you should be good to go.
