### ISSUE TITLE
Not able to load mbtiles

### ISSUE THREAD

**Issue by muruganandham** [Esri/arcgis-runtime-samples-ios#349]
Not able to load `mbtiles` in any layer using  arcgis runtime sdk version 100.1 for iOS.  Is it possible to do that in new version of run time sdk. In old runtime SDK, i have used `AGSTiledServiceLayer` to load `mbtiles`. I can load only `tpk` files using `AGSArcGISTiledLayer`.

**Comment by tekoscott** [comment]
Was this ever answered, as I am experiencing similar issues.

**Comment by dg0yal** [comment]
We do not support the mbtiles format out-of-the-box.
You can implement a custom tiled layer that supports the format.
