### ISSUE TITLE
Missing Category Background Image (Cloud & Portal)

### ISSUE THREAD

**Issue by esreli** [Esri/arcgis-runtime-samples-ios#358]
Upon launching the samples app, the user is presented with a categories page. The 'Cloud & Portal' category is missing a background image.

It's collection view is attempting to find an image with the name 'Cloud & Portal_bg' within the app bundle's image assets but there is no image.

![screen shot 2018-05-09 at 1 03 10 pm](https://user-images.githubusercontent.com/33433113/39837001-02ebff0e-538a-11e8-98e5-71aa95c065fb.png)

**Comment by dg0yal** [comment]
@saratchandrakarumuri this should be fixed

**Comment by saratchandrakarumuri** [comment]
background icon is now displayed for `cloud and portal` menu
