### ISSUE TITLE
Unexpected behavior for sample: Layers -> Export Tiles

### ISSUE THREAD

**Issue by esreli** [Esri/arcgis-runtime-samples-ios#359]
When first zooming in to the max scale and then attempting to 'Export Tiles' a user is presented with the error "Min scale and max scale cannot be the same".

A user should feasibly be able to zoom to a scale that the map allows in this sample (1155581.108577) and still be able to export tiles.

**Comment by yo1995** [comment]
This should have been fixed in the #986 PR.
