### ISSUE TITLE
Bug in sample: Features -> Feature Layer Query

### ISSUE THREAD

**Issue by esreli** [Esri/arcgis-runtime-samples-ios#360]
I've encountered a bug where a valid state in the feature layer query is not selected. To reproduce this, follow these steps:

1) Type 'Dakota' in the search bar and press enter -> the map **does** select the outline combined geometries of both North & South Dakota

2) Clear the contents of the search bar

3) Type 'North Dakota' in the search bar and press enter -> the map **should** select the outline geometry of just North Dakota but instead removes all selections. Using the debugger, it is confirmed that the query did in fact return a single feature result, the North Dakota feature but does not select this feature.

**Comment by dg0yal** [comment]
this is now fixed
