### ISSUE TITLE
Add Generalize operation to Geometry Sample

### ISSUE THREAD

**Issue by dg0yal** [Esri/arcgis-runtime-samples-ios#40]
for v10.2.3

**Comment by yo1995** [comment]
Seems we already have a sample for the `AGSGeometryEngine.generalizeGeometry` API. Do we close this issue? 
- https://github.com/Esri/arcgis-runtime-samples-ios/blob/v.next/arcgis-ios-sdk-samples/Geometry/Densify%20and%20generalize/DensifyAndGeneralizeViewController.swift

**Comment by yo1995** [comment]
Close due to inactivity. Reopen if need an update.
