### ISSUE TITLE
EditFeatures(Connected) sample missing creationMode

### ISSUE THREAD

**Issue by duanepfeiffer** [Esri/arcgis-runtime-samples-ios#407]
In the sample, popupsViewController sketchEditorFor() delegate method does not specify the creationMode.  This sounds like an error in the sample code.  Without specifying creationMode, I was only able to draw point features.

Referring to this sample:  [https://linkprotect.cudasvc.com/url?a=https%3a%2f%2fdevelopers.arcgis.com%2fios%2flatest%2fswift%2fsample-code%2fedit-features-connected-.htm&c=E,1,DvatLBPWNjWxH8DHSnU3zVM9qTmEWDBax6F0di1QoUTKYvq2j7UQ-0Z7bUa0x5ib34c0Cn48_5tKH2dLn4AS6ftgAHwXtJD1saJsgDNU&typo=1](url)

**Comment by yo1995** [comment]
Close due to inactivity.
