### ISSUE TITLE
Movement Track on Map

### ISSUE THREAD

**Issue by Hamza123Imran** [Esri/arcgis-runtime-samples-ios#414]
How can i get the track on the map when i'm moving?

**Comment by esreli** [comment]
Hi @Hamza123Imran. Would you please clarify your question? 

Actually, I encourage you to take questions like this over to our [GeoNet iOS SDK community page](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-ios) where we monitor and actively answer developer questions.

In the meantime and without more clarification from your question, perhaps the following answer might help get you along?

If you would like to track the visible area of the map view as a user interacts with the map (pans, zooms, rotates, etc), you could set an key value observer on the `AGSMapView`'s [visibleArea](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-ios) property. This property represents the extent of the map that is currently visible within the map view.

Additionally, there are a number of [delegate methods](https://developers.arcgis.com/ios/latest/api-reference/protocol_a_g_s_geo_view_touch_delegate-p.html) for tracking touches on an `AGSMapView`.

_Because your inquiry is a question and not an Issue, I will be closing this issue out. Please feel free to continue to reach out to the SDK team over at the GeoNet link provided above and we can help you solve the problems you have. Thanks!_
