### ISSUE TITLE
Custom Sketching in ArcGis Map

### ISSUE THREAD

**Issue by Hamza123Imran** [Esri/arcgis-runtime-samples-ios#430]
How can we make custom sketch on the map rather than using the default shapes? For example, if user want to give its area location he/she should sketch his/her way on the map custom.

**Comment by dg0yal** [comment]
@Hamza123Imran We support that using freehand sketch. See sample code https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Display%20information/Sketch%20on%20the%20map
