### ISSUE TITLE
Progress not tracked properly

### ISSUE THREAD

**Issue by codingmanu** [Esri/arcgis-runtime-samples-ios#479]
Using the sample code to export tiles but using a complex polygon instead of an extent (buffer of something similar to a river). Getting a rather large export size (800MB+).

My issue is when tracking progress. It starts tracking 5%, then 10%, then waits for a while and jumps to 30%, 50% after a while and a few minutes later when the full download is done, it jumps to 100% and the task is finished.

I can export the files just fine, but tracking the progress this way makes the user think the download is stuck.

Any ideas on what could be happening?

Code I'm using for this: [LINK](https://gist.github.com/codingmanu/1bc71598a0b286411bcc1f5b655f952f)

**Comment by codingmanu** [comment]
1:48:45 PM Progress: 0.0
1:48:45 PM Completed count: 0
1:48:45 PM Total count: -1
1:48:51 PM Progress: 0.02
1:48:51 PM Completed count: 2
1:48:51 PM Total count: 100
1:48:52 PM Progress: 0.02
1:48:52 PM Completed count: 2
1:48:52 PM Total count: 100
1:48:52 PM Progress: 0.05
1:48:52 PM Completed count: 5
1:48:52 PM Total count: 100
1:48:55 PM Progress: 0.05
1:48:55 PM Completed count: 5
1:48:55 PM Total count: 100
1:48:55 PM Progress: 0.05
1:48:55 PM Completed count: 5
1:48:55 PM Total count: 100
1:48:59 PM Progress: 0.05
1:48:59 PM Completed count: 5
1:48:59 PM Total count: 100
1:48:59 PM Progress: 0.1
1:48:59 PM Completed count: 10
1:48:59 PM Total count: 100
1:49:01 PM Progress: 0.1
1:49:01 PM Completed count: 10
1:49:01 PM Total count: 100
1:49:01 PM Progress: 0.1
1:49:01 PM Completed count: 10
1:49:01 PM Total count: 100
1:49:06 PM Progress: 0.1
1:49:06 PM Completed count: 10
1:49:06 PM Total count: 100
1:49:06 PM Progress: 0.1
1:49:06 PM Completed count: 10
1:49:06 PM Total count: 100
1:49:11 PM Progress: 0.1
1:49:11 PM Completed count: 10
1:49:11 PM Total count: 100
1:49:11 PM Progress: 0.15
1:49:11 PM Completed count: 15
1:49:11 PM Total count: 100
1:49:16 PM Progress: 0.15
1:49:16 PM Completed count: 15
1:49:16 PM Total count: 100
1:49:16 PM Progress: 0.15
1:49:16 PM Completed count: 15
1:49:16 PM Total count: 100
1:49:21 PM Progress: 0.15
1:49:21 PM Completed count: 15
1:49:21 PM Total count: 100
1:49:21 PM Progress: 0.15
1:49:21 PM Completed count: 15
1:49:21 PM Total count: 100
1:49:26 PM Progress: 0.15
1:49:26 PM Completed count: 15
1:49:26 PM Total count: 100
1:49:26 PM Progress: 0.15
1:49:26 PM Completed count: 15
1:49:26 PM Total count: 100
1:49:31 PM Progress: 0.15
1:49:31 PM Completed count: 15
1:49:31 PM Total count: 100
1:49:31 PM Progress: 0.2
1:49:31 PM Completed count: 20
1:49:31 PM Total count: 100
1:49:36 PM Progress: 0.2
1:49:36 PM Completed count: 20
1:49:36 PM Total count: 100
1:49:36 PM Progress: 0.2
1:49:36 PM Completed count: 20
1:49:36 PM Total count: 100
1:49:41 PM Progress: 0.2
1:49:41 PM Completed count: 20
1:49:41 PM Total count: 100
1:49:41 PM Progress: 0.2
1:49:41 PM Completed count: 20
1:49:41 PM Total count: 100
1:49:46 PM Progress: 0.2
1:49:46 PM Completed count: 20
1:49:46 PM Total count: 100
1:49:46 PM Progress: 0.2
1:49:46 PM Completed count: 20
1:49:46 PM Total count: 100
1:49:51 PM Progress: 0.2
1:49:51 PM Completed count: 20
1:49:51 PM Total count: 100
1:49:51 PM Progress: 0.25
1:49:51 PM Completed count: 25
1:49:51 PM Total count: 100
1:50:01 PM Progress: 0.25
1:50:01 PM Completed count: 25
1:50:01 PM Total count: 100
1:50:01 PM Progress: 0.25
1:50:01 PM Completed count: 25
1:50:01 PM Total count: 100
1:50:11 PM Progress: 0.25
1:50:11 PM Completed count: 25
1:50:11 PM Total count: 100
1:50:11 PM Progress: 0.25
1:50:11 PM Completed count: 25
1:50:11 PM Total count: 100
1:50:21 PM Progress: 0.25
1:50:21 PM Completed count: 25
1:50:21 PM Total count: 100
1:50:21 PM Progress: 0.3
1:50:21 PM Completed count: 30
1:50:21 PM Total count: 100
1:50:31 PM Progress: 0.3
1:50:31 PM Completed count: 30
1:50:31 PM Total count: 100
1:50:31 PM Progress: 0.3
1:50:31 PM Completed count: 30
1:50:31 PM Total count: 100
1:50:41 PM Progress: 0.3
1:50:41 PM Completed count: 30
1:50:41 PM Total count: 100
1:50:41 PM Progress: 0.3
1:50:41 PM Completed count: 30
1:50:41 PM Total count: 100
1:50:51 PM Progress: 0.3
1:50:51 PM Completed count: 30
1:50:51 PM Total count: 100
1:50:51 PM Progress: 0.3
1:50:51 PM Completed count: 30
1:50:51 PM Total count: 100
1:50:51 PM Progress: 0.3
1:50:51 PM Completed count: 30
1:50:51 PM Total count: 100
1:50:51 PM Progress: 0.5
1:50:51 PM Completed count: 50
1:50:51 PM Total count: 100
1:58:28 PM Progress: 1.0
1:58:28 PM Completed count: 100
1:58:28 PM Total count: 100

**Comment by dg0yal** [comment]
Looks like the transition upto 50% is more or less incremental over a 2 min period.
Then the next progress isn't reported for a whole 8 mins at which point it is 100%. That doesn't seem right. We do progressively delay the status check for jobs that take long to complete in order to prevent firing too many requests, but we shouldn't be going dark for 8 mins.

**Comment by nixta** [comment]
You could try this: When you get your job back, set up KVO on the `AGSJob.progress` property and call your `trackProgress()` method from there. Remember that KVO doesn't fire on the main thread, so be sure to dispatch over to it since you're doing UI work through `SVProgressHUD`.

**Comment by yo1995** [comment]
Close due to inactivity.
