### ISSUE TITLE
Improve Search Engine using Trie data structure

### ISSUE THREAD

**Issue by esreli** [Esri/arcgis-runtime-samples-ios#484]
Currently the samples search engine is powered by indexing the README of every sample into a dictionary of words found in the READMEs (keys) with their associated sample(s) (values). Because a dictionary uses a hash, this is an efficient system to look up values based on their keys.

However, a user might have the expectation that they will receive live results for their query as they type in the search bar. For instance, if they have thus-far typed "**Featu**" they might expect a list of results that include "**Featu**re", "**Featu**reTable", "**Featu**reLayer". Currently this is not the case and only when the full string is typed (the dictionary key) are results returned.

The sample application could leverage a [Trie](https://en.wikipedia.org/wiki/Trie). This data structure can be used to return all searches that match the current text as well as all other indexed possibilities that prefix with the search string.

Taking it further, the sample application could leverage a [Suffix Tree](https://en.wikipedia.org/wiki/Suffix_tree). This data structure is similar to a Trie but treats the search text potentially as a suffix as well, giving the added benefit of searching keys that contain the search text string instead of just begin with it. With a suffix tree, results for a search string such as "**Featu**" would include "**Featu**re", "**Featu**reTable", "**Featu**reLayer" as well as "AGS**Featu**re", "AGS**Featu**reTable", "AGS**Featu**reLayer"

`SearchEngine` could replace `wordsDictionary:[String: [String]]` with the built Trie structure. Additionally, the Trie structure could be built for thread safety using a `DispatchQueue`.

**Comment by dg0yal** [comment]
@esreli thanks for the suggestion. We recently improved the search implementation (Oct-ish) and U/X. The scenario you described does yield useful results now.

**Comment by esreli** [comment]
Ah thank you, it works great now.
