### ISSUE TITLE
Geofence trigger

### ISSUE THREAD

**Issue by serbanb** [Esri/arcgis-runtime-samples-ios#550]
Hi, I did not find any example on how to trigger a call to a delegate or a notification when the device enters or exits a defined area on a map. The area can be either a center point with a radius or a polygon defined by multiple points or something. I did not find any help in the ArcGis iOS SDK API Reference either. A hint on where to start is also appreciated. 
Thanks

**Comment by serbanb** [comment]
I found how to do Geofencing, using AGSGeometryEngine class.

**Comment by dg0yal** [comment]
@serbanb while you can certainly use AGSGeometryEngine to compute whether a point is inside or intersects a polygon, you could also consider using Apple's location manager apis with regions https://developer.apple.com/documentation/corelocation/monitoring_the_user_s_proximity_to_geographic_regions

ArcGIS Runtime does not yet provide any location based triggers or region monitoring functionality.

@alpascual had cooked up a demo on how this could be achieved using custom code built on top of runtime. Perhaps he can share that
