### ISSUE TITLE
render many Graphic in GraphicsLayer

### ISSUE THREAD

**Issue by hanchao** [Esri/arcgis-runtime-samples-ios#58]
I put many Graphic(20,000 polygons) into GraphicsLayer, then received memory warning.  how can I render so many Graphic?

**Comment by nyekimov** [comment]
Do not do it, it's a bad practice. Use clusters. Load graphics only on demand. When a user navigates to the smallest cluster and use AGSUniqueValueRenderer

**Comment by dg0yal** [comment]
Graphics are held entirely in memory. You will eventually hit a wall depending upon how many attributes and how complex geometries are for the graphics.
Try using feature layers instead. They keep the data on disk in a geodatabase so are much more efficient in terms of memory, but as you add more and more data it'll take longer to display them on the map.
