### ISSUE TITLE
unable to load XML in WMTS in iOS(Swift 4)

### ISSUE THREAD

**Issue by ShayanSolution** [Esri/arcgis-runtime-samples-ios#618]
Hi,
I am trying to run WMTS sample. i am using this xml for getCapabilities in below URL:

https://api.lantmateriet.se/open/topowebb-ccby/v1/wmts/token/172d422a3e65e5010d95ac5fc27eda/?request=getcapabilities&service=wmts

When i am using this in browser, its giving me proper xml response,BUT in app swift code says invalid XML provided (For Ref: find attached Image below)

Please guide about that how to handle "getcapabilities" in Swift for URL because in sample code for JavaScript its Obvious but not clear for Swift Coding.

We are waiting for early response.
Thank You.
![whatsapp image 2018-12-06 at 6 25 47 pm](https://user-images.githubusercontent.com/25619/49806506-bf784300-fd79-11e8-951a-fb677ebb8599.jpeg)

**Comment by dg0yal** [comment]
We'll look into this. Possibly a bug on our end

**Comment by pgruenler** [comment]
As part of sending out the "getcapabilities" request our code cleans up the URL.  Our experience has been that the clean-up we do makes the URL look more like what the URL standards specify and the examples we've seen.  Unfortunately, in this case our clean-up is causing some problems with the server you are using.  Our API does allow you to omit the "getcapabilities" query from the URL and in this case that works for the service you are using.  Here's what the line in the sample would look like - `private let WMTS_SERVICE_URL = URL(string: "https://api.lantmateriet.se/open/topowebb-ccby/v1/wmts/token/172d422a3e65e5010d95ac5fc27eda/")!`

**Comment by yo1995** [comment]
Close due to inactivity.
