### ISSUE TITLE
Provide sample TPK in Web Mercator

### ISSUE THREAD

**Issue by nixta** [Esri/arcgis-runtime-samples-ios#62]
The [San Francisco sample TPK](https://github.com/Esri/arcgis-runtime-samples-ios/blob/master/Data/tile%20package/SanFrancisco.tpk) is currently in WGS84. This looks decidedly odd to anyone used to seeing online maps these days.

Would be great to provide a Web Mercator version.

**Comment by yo1995** [comment]
Close due to inactivity.
