### ISSUE TITLE
How to change Point_Assets colour in Esri maps in swift ?

### ISSUE THREAD

**Issue by NaveeniOS** [Esri/arcgis-runtime-samples-ios#657]
Actually i need to change Point_Assets colour and Line_Assets colour , am getting those points and lines from AGSServiceFeatureTable with url.  Please find the attached image for reference.

<img width="454" alt="5bzjg" src="https://user-images.githubusercontent.com/46988917/53155815-de018280-35e3-11e9-924c-c6e4157c1201.png">

**Comment by nixta** [comment]
The [`AGSFeatureLayer`](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_feature_layer.html) you create for each layer has a [`renderer`](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_feature_layer.html#a794abda4fa045232c652c3f3b8007a16) on it which is defined by the source service. You can interrogate that renderer and modify or replace it. See [`AGSRenderer`](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_renderer.html).

From the image above it _looks_ like an [`AGSSimpleRenderer`](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_simple_renderer.html) (one [`AGSSymbol`](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_symbol.html) for all features in the layer), but note that there are various different subclasses that the service could define.

See these samples:

* https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Display%20information/Simple%20renderer
* https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Display%20information/Simple%20marker%20symbol
* https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Display%20information/Picture%20marker%20symbols
* https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Display%20information/Unique%20value%20renderer
