### ISSUE TITLE
Only one layer in TiledLayer

### ISSUE THREAD

**Issue by alexllao** [Esri/arcgis-runtime-samples-ios#674]
The WMS server with which we work only leaves a call to a tile every time, with a height and width of the entire screen. Is there any way to do it this way in the AGSArcGISTiledLayer? I attach a call to the WMS server and an image where it is indicated that it is the right thing and not the correct one.

![Screenshot_2019-03-22 Portal de la Dirección General del Catastro](https://user-images.githubusercontent.com/8004573/54816194-f07ae480-4c93-11e9-8b72-f47df93f6362.png)

https://ovc.catastro.meh.es/Cartografia/WMS/ServidorWMS.aspx?&SERVICE=WMS&VERSION=1.1.1&LAYERS=Catastro&STYLES=&FORMAT=image/png&TRANSPARENT=FALSE&SRS=EPSG:3857&REQUEST=GetMap&BBOX=-372445.7394908919,4915968.629157396,20134.837781773254,5138553.25552383&WIDTH=1284&HEIGHT=728

Thank you.

**Comment by nixta** [comment]
Hi.

[`AGSArcGISTiledLayer`](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_arc_g_i_s_tiled_layer.html) is meant to adhere to a tiling scheme to obtain tiles for the map. I think what you should use instead is the [`AGSWMSLayer`](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_w_m_s_layer.html). You should be able to pass in this link to use the above service (see [`initiWithURL:layerNames()`](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_w_m_s_layer.html#a97c51c3a3f76710d574379b4f73ce9f5)):

* https://ovc.catastro.meh.es/Cartografia/WMS/ServidorWMS.aspx?request=GetCapabilities&service=WMS

Does that answer your question?

**Comment by alexllao** [comment]
Hi! How can i get bbox coordinates to add in url request? Thnks a lot!

**Comment by alexllao** [comment]
This night i will test this example with my wms server. Thnks

**Comment by nixta** [comment]
> Hi! How can i get bbox coordinates to add in url request? Thnks a lot!

To use the WMS service in the Map View, you won't send bbox coordinates. The `AGSWMSLayer` will take care of adding those parameters for the current `AGSMapView` extent. Our layers work together with the `AGSMapView` to display the map.

If you separately need to get the image from the WMS service (e.g. to save locally as a PNG) then you should construct the URL yourself and make the request separately (outside of the runtime). If you need the bbox of the current `AGSMapView`, you can call [`AGSMapView.currentViewpointWIthType()`](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_geo_view.html#a8b4778a06f1278e65c3842ec2a636a8c) with a viewpointType of `.boundingGeometry` and read the extent of that geometry.

Perhaps I don't understand what you're trying to do here?

**Comment by alexllao** [comment]
Okis!!! Thnks

**Comment by alexllao** [comment]
Hi!! I've been test this code and it works!!!!

`let map = AGSMap(basemapType: .openStreetMap, latitude: 40.416775, longitude: -3.703790, levelOfDetail: 14)
        mapView.map = map
        let wmsServiceURL = URL(string: "https://ovc.catastro.meh.es/Cartografia/WMS/ServidorWMS.aspx?request=GetCapabilities&service=WMS")!
        let wmsServiceLayerNames = ["Catastro"]
        
        let wmsLayer = AGSWMSLayer(url: wmsServiceURL, layerNames: wmsServiceLayerNames)
        // wmsLayer.preferredImageFormat = .PNG24
        // wmsLayer.opacity = 0.5
        wmsLayer.showInLegend = true
        
        wmsLayer.customParameters = ["WIDTH":"\(mapView.frame.width)", "HEIGHT": "\(mapView.frame.height)"]
        
        wmsLayer.load { (error) in
            if let error = error {
                print(error.localizedDescription)
            } else if wmsLayer.loadStatus == .loaded {
                map.operationalLayers.add(wmsLayer)
            }
        }`

If i add customParameters layer no longer load.

**Comment by nixta** [comment]
Yeah. You shouldn't need to set the width and height. `AGSMapView` and `AGSWMSLayer` will work together to set all that as you pan and zoom around the map. `customParameters` might typically be used for some custom authentication token. But for anything to do with the size of the map or area of the map, let the runtime handle all that.

**Comment by alexllao** [comment]
Oks!!! Now I have to investigate how to get the central coordinates of the map, or get the latitut and longitude when I click on the map.

**Comment by nixta** [comment]
Cool. You might consider running through some fo the [iOS DevLabs](https://developers.arcgis.com/labs/browse/?topic=any&product=iOS).

Center of the map can be got with AGSMapView.getCurrrentViewpointWithType() but use CenterAndScale. The viewpoint geometry will be the center.

To see where you tapped, use the AGSGeoViewTouchDelegate. See [here](https://github.com/Esri/arcgis-runtime-samples-ios/blob/master/arcgis-ios-sdk-samples/Maps/Identify%20layers/IdentifyLayersViewController.swift#L65-L73) and [here](url). mapPoint will be a point in the map's spatial reference.

Questions like that will be better off being posted in the [Runtime SDK forum](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-ios/content).

**Comment by alexllao** [comment]
Thnks a lot!
