### ISSUE TITLE
WMS GetFeatureInfo

### ISSUE THREAD

**Issue by alexllao** [Esri/arcgis-runtime-samples-ios#678]
If I want to change the Request "GetMap" to "GetFeatureInfo" and get the html it returns there is some method in the library? It return HTML info.

Attachment shows:

https://ovc.catastro.meh.es/Cartografia/WMS/ServidorWMS.aspx?&SERVICE=WMS&VERSION=1.1.1&LAYERS=Catastro&STYLES=&FORMAT=image/png&TRANSPARENT=TRUE&SRS=EPSG:3857&REQUEST=GetFeatureInfo&QUERY_LAYERS=Catastro&FEATURE_COUNT=10&INFO_FORMAT=text/ html & BBOX = 77081.05176575505,4978963.533688548,79517.48204234504,4980071.870598684 & WIDTH = 1020 & HEIGHT = 464 & X = 810 & Y = 288

Thnks a lot!

**Comment by dg0yal** [comment]
This can be done by using `Mapview.identifyLayer()` for the WMS layer. It will make a GetFeatureInfo request and return results with the HTML content
