### ISSUE TITLE
callout.setCustomView()can't use

### ISSUE THREAD

**Issue by xingyufeifan** [Esri/arcgis-runtime-samples-ios#699]
CustomView show location is wrong

**Comment by philium** [comment]
Are you using 100.5? As described in the [release notes](https://developers.arcgis.com/ios/latest/swift/guide/release-notes.htm#ESRI_SECTION1_E5C4E398DBC145B1A991A4CF0C95B09F), the behavior of callouts with custom views has changed:

> A callout with a custom view **now uses AutoLayout to size itself** to fit that view. A custom view will need to either provide an [intrinsic content size](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/ViewswithIntrinsicContentSize.html) or have enough constraints to define it's size. Previously the size of the view's frame was used to size the callout. For views without an intrinsic content size, that same behavior can still be achieved by adding width and height constraints to the view.

**Comment by xingyufeifan** [comment]
yes, I am using 100.5. My custom view has been set size. The callout custom view is not in the callout bubble
![QQ图片20190419090916](https://user-images.githubusercontent.com/20453971/56399835-fe1b8e00-6282-11e9-8477-9c7bb0884b11.png)

**Comment by philium** [comment]
> My custom view has been set size.

How are you sizing your custom view?

**Comment by lushangshu** [comment]
Hi Philium, Can you provide an example on how to create a customView using pure code without xib file or storyboard? I do not know how to fix my custom callout view.

**Comment by philium** [comment]
@lushangshu One example is the [Identify KML Features](https://github.com/Esri/arcgis-runtime-samples-ios/blob/85ba2bad2a17945c9a95da22175a9f3717b17e35/arcgis-ios-sdk-samples/Layers/Identify%20KML%20features/IdentifyKMLFeaturesViewController.swift#L57) sample (introduced in 100.5), which uses a self-sizing `UITextView` as the callout's custom view. Another example is the [Project](https://github.com/Esri/arcgis-runtime-samples-ios/blob/1674c9865f5e91ef668698d563ac25ceccd6d78e/arcgis-ios-sdk-samples/Geometry/Project/ProjectViewController.swift#L58) sample (to be introduced in 100.6), which uses a self-sizing `UIStackView` as the callout's custom view. The stack view is instantiated from a storyboard, but it would work the exact same way if the stack view was instantiated and configured with the labels in code. I hope that helps.

**Comment by lushangshu** [comment]
@philium Thanks a lot, I used Masonry[https://github.com/SnapKit/Masonry](url) solving that problem. It is quite easy to size my custom view setting my view's width and height.
