### ISSUE TITLE
Build Error- Use of undeclared type 'Result'

### ISSUE THREAD

**Issue by sandeeps727** [Esri/arcgis-runtime-samples-ios#797]
Hi,
Just cloned the repo for 100.6.0  and trying to build it but getting this error- "Use of undeclared type 'Result'' in many classes like ControlAnnotationSublayerVisibilityViewController ,MapSelectionTableViewController etc. Tried both manual as well cocoa pod.
I am using XCode 10.1 and Swift 4.2 . Any suggestions ? Thanks
-Sandeep

**Comment by philium** [comment]
Thank you for your question. As stated in the Requirements section of the [README](https://github.com/Esri/arcgis-runtime-samples-ios/blob/master/README.md), the minimum Xcode version is now 11.0.
