### ISSUE TITLE
About 100.2 and 100.6 specifications and architecture.

### ISSUE THREAD

**Issue by tkamiya0625** [Esri/arcgis-runtime-samples-ios#824]
Hello, sorry if this is the wrong place to ask, Is there any difference in the rendering of the map when using mmpk in 100.2 and 100.6?

Is the following perception wrong?
100.2 displays map data in a range not displayed on the terminal screen (it develops the data on the memory).
On the other hand, in 100.6, the range that is not displayed on the terminal screen is not it develops the data on the memory, so if you move the map, the map will be redrawn frequently, so it may be a jerky movement.

**Comment by dg0yal** [comment]
We constantly tweak, tune, and refine ways to render the map. Generally, we expect performance to either stay constant or improve from release to release, with the same type and amount of map data. Sometimes, as we add more rendering capabilities, you might see additional types of data render on the map that was possibly ignored or downgraded previously - this might change the percieved performance, but it is something we'd look at and investigate.

If you are seeing map navigation & interactions become less fluid with a recent releases, it will be helpful if you can describe what you're seeing and provide us a repro case that we can debug
