### ISSUE TITLE
OfflineFeatureEditing swift version missing storyboard

### ISSUE THREAD

**Issue by alpascual** [Esri/arcgis-runtime-samples-ios#85]
After downloading the geodatabase, the user clicks the + button to add a new feature and get the error:
NSInvalidArgumentException', reason: 'Could not find a storyboard named 'Offline Feature Editing' in bundle NSBundle
@singhgag @dg0yal

**Comment by singhgag** [comment]
@dg0yal seems like the name of the storyboard was changed to Main.storyboard. Fixed it and a couple of other issues.

**Comment by singhgag** [comment]
Created a PR

**Comment by dg0yal** [comment]
@alpascual Pl. verify
