### ISSUE TITLE
iOS 13.3.1 Cannot be debugged by phone

### ISSUE THREAD

**Issue by Mebsunny** [Esri/arcgis-runtime-samples-ios#855]
following errors

<img width="1229" alt="error" src="https://user-images.githubusercontent.com/16472481/79935172-d3ac7400-8486-11ea-9305-44a0e1e8c14c.png">

**Comment by yo1995** [comment]
Hi, could you provide more details? Much appreciated! 🙂   
E.g. Are you using CocoaPods installation or SDK installation, what versions are your Xcode and macOS on, etc.?

**Comment by Mebsunny** [comment]
> Hi, could you provide more details? Much appreciated! 🙂
> E.g. Are you using CocoaPods installation or SDK installation, what versions are your Xcode and macOS on, etc.?
CocoaPods installation

**Comment by Mebsunny** [comment]
> Hi, could you provide more details? Much appreciated! 🙂
> E.g. Are you using CocoaPods installation or SDK installation, what versions are your Xcode and macOS on, etc.?

CocoaPods installation
CocoaPods version : 1.9.1
Xcode version : 11.3
Phone :  iPhone 8 plus
Mac OS : 10.15.4

**Comment by Mebsunny** [comment]
> Hi, could you provide more details? Much appreciated! 🙂
> E.g. Are you using CocoaPods installation or SDK installation, what versions are your Xcode and macOS on, etc.?

The reason has been found because the free Apple ID cannot install the project with framework on iOS 13.3.1.
