### ISSUE TITLE
Esri VectorTiledLayer refresh problem

### ISSUE THREAD

**Issue by ikbalyasar** [Esri/arcgis-runtime-samples-ios#916]
Hello there,
I added a vector map to my application, even though this map is updated in the background, I cannot see the current map when I open the application. data comes from cache.
Is there a structure that I can renew like the dynamic service of SDK and pull the instant style file from the server? I don't want the phone to cache.

Have updated hourly from vector data.

**Comment by nixta** [comment]
Hi @ikbalyasar. Thanks for the question.

Just to clarify, are you updating the style, or the map data?

Regardless, if you're working with a downloaded tile cache and resource set, it's up to you to pull a fresh set down.

In the case of the tile cache, we don't support downloading just the updated tiles - you would have to generate and download the cache again.

If you are just interested in an updated style, then you can call [`AGSExportVectorTilesTask.exportStyleResourceCacheJobWithDownloadDirectory()`](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_export_vector_tiles_task.html#ac51fb7a650bb19f02ce725a8cab902ee). The job that's returned will download the current styles. You would then have to re-add the vector tile layer to your map, specifying the tile cache you already had, with the new style resource set.

Does that help?

**Comment by ikbalyasar** [comment]
Hi,
I am add on my map.
url : .......rest/services/Hosted/MyMobil/VectorTileServer
```
myVectorLayer = AGSArcGISVectorTiledLayer(url: url!) 
self.mapView.map?.operationalLayers.add(myVectorLayer!)
```

I add and display the vector map as above.
After 1 hour, this map data is updated on the server again. The colors of the vector data have changed in the style file. But I still see the old colored data.
For example; I generate the traffic density data as a vector every 5 minutes. It creates different colors in every data I produce according to the traffic data density. But in my application it cannot see the current style file and continues to load from the cache. The data of 2 hours ago appears.

**Comment by nixta** [comment]
Ok. I see.

This doesn't appear to have anything to do with the Samples app. Seems like a question that should really be asked over at the [GeoNet Forum](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-ios/content).

I'll close this issue so it doesn't interfere with other samples, but we can continue to discuss here if you like.

**Comment by nixta** [comment]
To clarify:
* You are using `AGSArcGISVectorTiledLayer` to display a vector tile service found at .......rest/services/Hosted/MyMobil/VectorTileServer
* You are updating the vector tile service every 1 hour.

I am not sure what you mean by `The colors of the vector data have changed in the style file` but I think you are conflating the tile cache with the style definition? That is, you keep the style file the same, but update the tile cache data?

> In short, I want to retake the style from the server and get the current style in every pan and zoom event. Like ESRI Dynamic Services.

Are you sure you don't want to get the latest data?

**Comment by ikbalyasar** [comment]
Nixta,

**Comment by ikbalyasar** [comment]
Hi;
Update style my reason is that each geometry is obvious in the color type style.

I read this style :  VectorTileServer/resources/styles/root.json 

[https://pasteboard.co/JiSFStK.png]

As you can see in the picture, the line colors need to change as the traffic density changes, but it does not change in the mobile application even though it changes on the server. It keeps the cache in its old style data.
I also want to recolor according to this style file every time, not from the cache.

**Comment by nixta** [comment]
Does each street segment not have a traffic density attribute that is used by the style file to color the data?

Are you saying the content of that `root.json` file changes every hour?

If so, please can you share two copies of the different `root.json` files so I can understand?

**Comment by nixta** [comment]
To clarify my confusion: typically the style data would describe something like this:

* Low density: Green line solid 2pt width
* Medium density: Orange line solid 2pt width
* High density: Red line solid 2.5pt width

And then the data in the tiles would have an attribute that says "Low density", "Medium density" or "High density" and the style rule above is applied at render time.

That way you never change the style, just the data (which is provided in the tile cache).

**Comment by ikbalyasar** [comment]
Ok. I share my root.json.

Although the "line-color" data changes on a server every 5 minutes, it does not change in the mobile application. It doesn't refresh the style. for example, it remains in the style color 3 hours ago.

paint ": {" line-color "" # FF0000 "," line-width ": 3.05882}

root.json

{"version":8,"sprite":"../sprites/sprite","glyphs":"../fonts/{fontstack}/{range}.pbf","sources":{"esri":{"type":"vector","url":"../../"}},"layers":[{"id":"ANAARTER_(1010)_1000K/Veri Yok","type":"line","source":"esri","source-layer":"ANAARTER_(1010)_1000K","filter":["==","_symbol",5],"minzoom":8,"maxzoom":12,"layout":{"line-join":"round"},"paint":{"line-color":"#B2B2B2","line-width":2.66667}},{"id":"ANAARTER_(1010)_1000K/Serbest/0","type":"line","source":"esri","source-layer":"ANAARTER_(1010)_1000K","filter":["==","_symbol",4],"minzoom":8,"maxzoom":12,"layout":{"line-join":"round"},"paint":{"line-color":"#76FF03","line-width":2.54902}},{"id":"ANAARTER_(1010)_1000K/Açık/0","type":"line","source":"esri","source-layer":"ANAARTER_(1010)_1000K","filter":["==","_symbol",3],"minzoom":8,"maxzoom":12,"layout":{"line-join":"round"},"paint":{"line-color":"#5CB044","line-width":2.54902}},{"id":"ANAARTER_(1010)_1000K/Akıcı/0","type":"line","source":"esri","source-layer":"ANAARTER_(1010)_1000K","filter":["==","_symbol",2],"minzoom":8,"maxzoom":12,"layout":{"line-join":"round"},"paint":{"line-color":"#FF9800","line-width":2.54902}},{"id":"ANAARTER_(1010)_1000K/Yoğun/0","type":"line","source":"esri","source-layer":"ANAARTER_(1010)_1000K","filter":["==","_symbol",1],"minzoom":8,"maxzoom":12,"layout":{"line-join":"round"},"paint":{"line-color":"#FF0000","line-width":2.54902}},{"id":"ANAARTER_(1010)_1000K/Çok Yoğun/0","type":"line","source":"esri","source-layer":"ANAARTER_(1010)_1000K","filter":["==","_symbol",0],"minzoom":8,"maxzoom":12,"layout":{"line-join":"round"},"paint":{"line-color":"#8B0000","line-width":2.54902}},{"id":"ANAARTER_(1010,1020,1030)_72K/Veri Yok","type":"line","source":"esri","source-layer":"ANAARTER_(1010,1020,1030)_72K","filter":["==","_symbol",5],"minzoom":12,"maxzoom":13,"layout":{"line-join":"round"},"paint":{"line-color":"#B2B2B2","line-width":2.66667}},{"id":"ANAARTER_(1010,1020,1030)_72K/Serbest/0","type":"line","source":"esri","source-layer":"ANAARTER_(1010,1020,1030)_72K","filter":["==","_symbol",4],"minzoom":12,"maxzoom":13,"layout":{"line-join":"round"},"paint":{"line-color":"#76FF03","line-width":3.05882}},{"id":"ANAARTER_(1010,1020,1030)_72K/Açık/0","type":"line","source":"esri","source-layer":"ANAARTER_(1010,1020,1030)_72K","filter":["==","_symbol",3],"minzoom":12,"maxzoom":13,"layout":{"line-join":"round"},"paint":{"line-color":"#5CB044","line-width":3.05882}},{"id":"ANAARTER_(1010,1020,1030)_72K/Akıcı/0","type":"line","source":"esri","source-layer":"ANAARTER_(1010,1020,1030)_72K","filter":["==","_symbol",2],"minzoom":12,"maxzoom":13,"layout":{"line-join":"round"},"paint":{"line-color":"#FF9800","line-width":3.05882}},{"id":"ANAARTER_(1010,1020,1030)_72K/Yoğun/0","type":"line","source":"esri","source-layer":"ANAARTER_(1010,1020,1030)_72K","filter":["==","_symbol",1],"minzoom":12,"maxzoom":13,"layout":{"line-join":"round"},"paint":{"line-color":"#FF0000","line-width":3.05882}},{"id":"ANAARTER_(1010,1020,1030)_72K/Çok Yoğun/0","type":"line","source":"esri","source-layer":"ANAARTER_(1010,1020,1030)_72K","filter":["==","_symbol",0],"minzoom":12,"maxzoom":13,"layout":{"line-join":"round"},"paint":{"line-color":"#8B0000","line-width":3.05882}},{"id":"ANAARTER_(1010,1020,1030,1040)_36K/Veri Yok","type":"line","source":"esri","source-layer":"ANAARTER_(1010,1020,1030,1040)_36K","filter":["==","_symbol",5],"minzoom":13,"maxzoom":14,"layout":{"line-join":"round"},"paint":{"line-color":"#B2B2B2","line-width":2.66667}},{"id":"ANAARTER_(1010,1020,1030,1040)_36K/Serbest/0","type":"line","source":"esri","source-layer":"ANAARTER_(1010,1020,1030,1040)_36K","filter":["==","_symbol",4],"minzoom":13,"maxzoom":14,"layout":{"line-join":"round"},"paint":{"line-color":"#76FF03","line-width":3.56863}},{"id":"ANAARTER_(1010,1020,1030,1040)_36K/Açık/0","type":"line","source":"esri","source-layer":"ANAARTER_(1010,1020,1030,1040)_36K","filter":["==","_symbol",3],"minzoom":13,"maxzoom":14,"layout":{"line-join":"round"},"paint":{"line-color":"#5CB044","line-width":3.56863}},{"id":"ANAARTER_(1010,1020,1030,1040)_36K/Akıcı/0","type":"line","source":"esri","source-layer":"ANAARTER_(1010,1020,1030,1040)_36K","filter":["==","_symbol",2],"minzoom":13,"maxzoom":14,"layout":{"line-join":"round"},"paint":{"line-color":"#FF9800","line-width":3.56863}},{"id":"ANAARTER_(1010,1020,1030,1040)_36K/Yoğun/0","type":"line","source":"esri","source-layer":"ANAARTER_(1010,1020,1030,1040)_36K","filter":["==","_symbol",1],"minzoom":13,"maxzoom":14,"layout":{"line-join":"round"},"paint":{"line-color":"#FF0000","line-width":3.56863}},{"id":"ANAARTER_(1010,1020,1030,1040)_36K/Çok Yoğun/0","type":"line","source":"esri","source-layer":"ANAARTER_(1010,1020,1030,1040)_36K","filter":["==","_symbol",0],"minzoom":13,"maxzoom":14,"layout":{"line-join":"round"},"paint":{"line-color":"#8B0000","line-width":3.56863}},{"id":"Tum_18K/Veri Yok","type":"line","source":"esri","source-layer":"Tum_18K","filter":["==","_symbol",5],"minzoom":14,"layout":{"line-join":"round"},"paint":{"line-color":"#B2B2B2","line-width":2.66667}},{"id":"Tum_18K/Serbest/0","type":"line","source":"esri","source-layer":"Tum_18K","filter":["==","_symbol",4],"minzoom":14,"layout":{"line-join":"round"},"paint":{"line-color":"#76FF03","line-width":5.09804}},{"id":"Tum_18K/Açık/0","type":"line","source":"esri","source-layer":"Tum_18K","filter":["==","_symbol",3],"minzoom":14,"layout":{"line-join":"round"},"paint":{"line-color":"#5CB044","line-width":5.09804}},{"id":"Tum_18K/Akıcı/0","type":"line","source":"esri","source-layer":"Tum_18K","filter":["==","_symbol",2],"minzoom":14,"layout":{"line-join":"round"},"paint":{"line-color":"#FF9800","line-width":5.09804}},{"id":"Tum_18K/Yoğun/0","type":"line","source":"esri","source-layer":"Tum_18K","filter":["==","_symbol",1],"minzoom":14,"layout":{"line-join":"round"},"paint":{"line-color":"#FF0000","line-width":5.09804}},{"id":"Tum_18K/Çok Yoğun/0","type":"line","source":"esri","source-layer":"Tum_18K","filter":["==","_symbol",0],"minzoom":14,"layout":{"line-join":"round"},"paint":{"line-color":"#8B0000","line-width":5.09804}}]}

**Comment by ikbalyasar** [comment]
@nixta  hi,
I think .pbf files are cached. Do I have a chance to keep it updated every time?

**Comment by nixta** [comment]
Thanks for your patience, @ikbalyasar. I'm checking with the team and will get back to you.

**Comment by nixta** [comment]
So it looks like you'd have to create a new identical layer, and remove the old layer to force the pbfs to be downloaded again. We'll look into providing an API to give more explicit control over this in the future.

**Comment by ikbalyasar** [comment]
@nixta  Thank you for the answer.

Do you have the opportunity to share sample code?

**Comment by nixta** [comment]
Something like this should work:

``` swift
if let currentVectorLayer = myVectorLayer,
    let newVectorLayer = currentVectorLayer.copy() as? AGSArcGISVectorTiledLayer,
    let index = self.mapView.map?.operationalLayers.index(of: currentVectorLayer) {
    self.mapView.map?.operationalLayers.insert(newVectorLayer, at: index)
    self.mapView.map?.operationalLayers.remove(currentVectorLayer)
}
```

In this case I am copying the layer you already have, finding out where that is in the layer order, adding the copy of the layer into the layer order at the appropriate point, and then removing the old layer.

The new layer should request the latest pbfs, regardless of what the old layer was storing.

If for some reason that doesn't work quite as expected, just create the new layer from the URL as you did the original.

Let me know how that works.

**Comment by nixta** [comment]
I suppose this could also work and is more succinct - I've never used the `replace` method on an array but it should work nicely:

```swift
if let currentVectorLayer = myVectorLayer,
    let newVectorLayer = currentVectorLayer.copy() as? AGSArcGISVectorTiledLayer,
    let index = self.mapView.map?.operationalLayers.index(of: currentVectorLayer) {
    self.mapView.map?.operationalLayers.replaceObject(at: index, with: newVectorLayer)
}
```

**Comment by ikbalyasar** [comment]
Hi;
The problem is not actually adding and deleting.
Sample;
I create vectorTile and add my map;
```
let url = URL (string: Constants.MapUrl.trafficVectorTile.rawValue)
trafficLayer = AGSArcGISVectorTiledLayer (url: url!)
Is self.mapview.map?.operationallayers.add(trafficLayer)
```

Then when I listen to the network connection;

https: //mylink/VectorTileServer/tile/8/96/149.pbf -2.9Kb
https: //mylink/VectorTileServer/tile/8/96/150.pbf -3.7Kb
https: //mylink/VectorTileServer/tile/8/96/151.pbf -**from disk cashe**
https: //mylink/VectorTileServer/tile/8/96/152.pbf -**from disk cashe**

I cannot catch the change because the data it pulled from the cache came before.

My wish is to get the data from the server on every request. I don't want the cache to read.

I share a sample screenshot from the web js page;
https://pasteboard.co/JjO7nfl.png

**Comment by nixta** [comment]
What is that screenshot from?

You cannot control the internal cache of the AGSArcGISVectorTileLayer, so if you want to force fresh tiles to be loaded, you need to create a new instance of the layer which has an empty cache and display that.

If you want to do that every time you zoom or pan the map, that could be messy, but you had said you wanted to do this every 5 minutes.

But if the above screenshot is showing iOS system level caching, you could try this:

``` swift
myVectorLayer = AGSArcGISVectorTiledLayer(url: url!) 
if let rc = AGSRequestConfiguration.global().copy() as? AGSRequestConfiguration {
    rc.requestCachePolicy = .reloadIgnoringLocalAndRemoteCacheData
    rc.shouldCacheResponse = false
    myVectorLayer?.requestConfiguration = rc
}
self.mapView.map?.operationalLayers.add(myVectorLayer!)
```

That won't do anything to clear out the layer's own internal cache, but if your screenshot is showing system-level caching, that should help.

**Comment by ikbalyasar** [comment]
@nixta 
Thank you very much.

It worked very well.

I couldn't find this part.

`AGSRequestconfiguration.global()`

İt's clear cashe this code.
`.reloadIgnoringLocalAndRemoteCacheData`

Thanks.

**Comment by nixta** [comment]
Great to hear!

Note there is the global `AGSRequestConfiguration` that affects everything in the app, and then you can override per service (which is what we did here). Any class that implements the `AGSRemoteResource` protocol will allow this.
