### ISSUE TITLE
Delegates not being called

### ISSUE THREAD

**Issue by aliawais** [Esri/arcgis-runtime-samples-ios#980]
AGSRouteTrackerDelegate methods are not getting called, following is SDK and other related information
Using ArcGIS-Runtime-SDK-iOS (100.7)
Xcode 11.7
iOS Simulator with iOS 13.7
iPhone X 13.4.1

Also, do we need to set data sources for real navigation? If yes, how to set instead of "AGSSimulatedLocationDataSource".

**Comment by yo1995** [comment]
In terms of setting real location, consider using [AGSCLLocationDataSource](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_c_l_location_data_source.html)

**Comment by aliawais** [comment]
@yo1995 Any example to how to set AGSCLLocationDataSource with other parameters as for AGSSimulatedLocationDataSource in the example.

Also the demo is not calling the delegates.

**Comment by yo1995** [comment]
> @yo1995 Any example to how to set AGSCLLocationDataSource with other parameters as for AGSSimulatedLocationDataSource in the example.

[`Navigate in AR`](https://github.com/Esri/arcgis-runtime-samples-ios/blob/master/arcgis-ios-sdk-samples/Augmented%20reality/Navigate%20in%20AR/NavigateARNavigatorViewController.swift) is a similar sample that uses real world location (from Apple, `AGSCLLocationDataSource`) as data source.

While it doesn't need a list of simulated location points, it works pretty much the same as the `AGSSimulatedLocationDataSource` in terms of other parameters.

> Also the demo is not calling the delegates.

Which sample are you referring to? The simulated location data source API has been changed, so to build with current `master` and see how it works, you'll need 100.9 SDK.

@nixta for more help.

**Comment by aliawais** [comment]
Thanks @yo1995 
We were using the sample code for the from ArcGIS Demo example that was using AGSSimulatedLocationDataSource, the example was working fine few weeks back, but now the same code is not calling delegates. I am not sure which ArcGIS version was initially used but current one is 100.7 in which the delegates are not called.

To implement for real world example, i would change the network analysis service, update stops to use real location and update data source in that example. But the example is not calling delegates so i am stuck. 

What is the minimum iOS version required for ArcGIS 100.9 as our app currently support iOS 11 and ArcGIS 100.9 does not support it.

**Comment by aliawais** [comment]
@nixta 
Can you help in why the delegates are not being called with the specifications given in first message. If thats is fixed i can update the data source and and stop and it should work.

**Comment by yo1995** [comment]
> Can you help in why the delegates are not being called with the specifications given in first message. If thats is fixed i can update the data source and and stop and it should work.

Thanks for reporting this. We received a similar [issue](https://community.esri.com/thread/260981-navigation) earlier today. Please wait for a more authoritative response from Nick. 🙂

**Comment by aliawais** [comment]
The sample works fine with SDK 100.6 but not with SDK 100.7. We were supporting iOS 11 onwards so that latest SDK we can use was 100.7. However we decided to use the latest SDK 100.9 and support iOS 12 onwards.

**Comment by aliawais** [comment]
Not sure what the issue is, I created new projects one with SDK 100.6 (iOS 11.0+) and one with SDK 100.9 (iOS 12.0+) copied 'NavigateRouteViewController' and 'NavigateRoute.storyboard' sample works fine in both projects. 
But when I copy the files to actual project it shows the route draws lines but does navigate nor does show text at top. Any idea?

**Comment by nixta** [comment]
Do you have any other code controlling the location display or grabbing the AGSLocationChangeHandlerDelegate? It seems like that connection may be getting disconnected.

**Comment by aliawais** [comment]
No for this screen. The issue i found is if I comment the code setting the license key the sample works. I hope for the actual project I just need to change stops and data source.

**Comment by nixta** [comment]
Ah. Navigation does require a Basic level license or higher.

Nick Furness
Esri | Product Manager: ArcGIS Runtime SDKs
________________________________

**Comment by yo1995** [comment]
@aliawais Hope your issue is resolved. 

With your (Lite) license, could you add the code below to the `AGSLocationChangeHandlerDelegate` of the sample code? It should display the error message when location get updated.

```swift
        routeTracker?.trackLocation(location) { [weak self] error in
            if let error = error {
                self?.setStatus(message: error.localizedDescription)
            }
        }
```

Thanks.

**Comment by aliawais** [comment]
@nixta 
Have pasted code for my **setNavigation** function

```
func setNavigation(with routeResult: AGSRouteResult) {
        // Set the route tracker
        routeTracker = makeRouteTracker(result: routeResult)

        let firstRoute = routeResult.routes.first!
        directionsList = firstRoute.directionManeuvers
        if let locationCoordinate = firstRoute.stops.first?.geometry?.toCLLocationCoordinate2D() {
            initialLocation = AGSLocation(clLocation: CLLocation(latitude: locationCoordinate.latitude, longitude: locationCoordinate.longitude))
        }

        // Create a route tracker location data source to snap the location display to the route.
        let routeTrackerLocationDataSource = AGSRouteTrackerLocationDataSource(routeTracker: routeTracker, locationDataSource: trackingLocationDataSource)

        // Set location display.
        mapView.locationDisplay.dataSource = routeTrackerLocationDataSource
        recenter()

        // Update graphics and viewpoint.
        let firstRouteGeometry = firstRoute.routeGeometry!
        updateRouteGraphics(remaining: firstRouteGeometry)
        updateViewpoint(geometry: firstRouteGeometry)
    }
```

**trackingLocationDataSource** is initialised as 
`let trackingLocationDataSource = AGSCLLocationDataSource()`

its delegate is set in a function called from **viewDidLoad()** as
```
trackingLocationDataSource.locationChangeHandlerDelegate = self
trackingLocationDataSource.start()
```

**AGSLocationChangeHandlerDelegate** function `func locationDataSource(_ locationDataSource: AGSLocationDataSource, locationDidChange location: AGSLocation)`

is only called once, have been driving with stops around my location, status text does not get updated and also user location does not change, the delegates are not getting called.

**Comment by nixta** [comment]
Have you confirmed you are using a Basic or higher license?

**Comment by aliawais** [comment]
Yes we have a license, and its set in AppDelegate

```
private func licenseESRI() {
        do {
            let result = try AGSArcGISRuntimeEnvironment.setLicenseKey("XXXX,none,XXXX")
            print("License Result : \(result.licenseStatus)")
        } catch {
            print("Error: \(error.localizedDescription)")
        }
    }
```

**Comment by nixta** [comment]
And you are certain it is not a Lite license? When you add the code @yo1995 provided above, you do see an error reported?

If you like, please DM me the license key over at GeoNet.

The Navigation API requires Basic license or higher. This has always been a requirement but was not technically enforced until 100.7.

**Comment by aliawais** [comment]
It shows 'Attempt to use an unlicensed extension'

**Comment by nixta** [comment]
Right. You need to use a Basic level license key to use the Navigation API.

See https://developers.arcgis.com/ios/latest/swift/guide/license-your-app.htm for more details.

**Comment by yo1995** [comment]
Please see the new sample code (#1070) for error handling. Feel free to re-open this issue if you have other questions.
